import Link from 'next/link'
import { ArrowLeft, FileText } from 'lucide-react'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50 py-20 px-4">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-blue-600 font-bold mb-8 hover:gap-3 transition-all">
          <ArrowLeft className="w-5 h-5" />
          Back to Home
        </Link>

        <div className="bg-white rounded-[2.5rem] shadow-xl border border-slate-200 p-10 md:p-16">
          <div className="flex items-center gap-4 mb-8">
            <div className="w-12 h-12 bg-blue-100 rounded-2xl flex items-center justify-center text-blue-600">
              <FileText className="w-6 h-6" />
            </div>
            <h1 className="text-3xl md:text-4xl font-black text-slate-900 tracking-tight">Terms of Service</h1>
          </div>

          <div className="prose prose-slate max-w-none space-y-6 text-slate-600">
            <p className="font-medium text-slate-900 italic">Last updated: April 30, 2026</p>
            
            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">1. Acceptance of Terms</h2>
              <p>By accessing or using ResumeMaster, you agree to be bound by these Terms of Service and all applicable laws and regulations.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">2. Use of Service</h2>
              <p>You agree to use the service only for lawful purposes and in accordance with these terms. You are responsible for maintaining the confidentiality of your account information.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">3. Subscriptions and Payments</h2>
              <p>Payments are processed via Razorpay. Subscriptions automatically renew unless cancelled. The 3-day trial requires a 1 Rs activation fee and will transition to a paid monthly plan unless cancelled before the trial ends.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">4. Intellectual Property</h2>
              <p>The service and its original content are and will remain the exclusive property of ResumeMaster and its licensors. Resumes generated by you are your intellectual property.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">5. AI Limitation of Liability</h2>
              <p>While our AI provides optimizations based on industry standards, we do not guarantee job interviews or employment. The final responsibility for the content and accuracy of your resume lies with you.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">6. Termination</h2>
              <p>We may terminate or suspend your account and access to the service immediately, without prior notice or liability, for any reason, including breach of these Terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">7. Changes to Terms</h2>
              <p>We reserve the right to modify or replace these terms at any time. Your continued use of the service after any changes constitutes acceptance of the new terms.</p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-slate-900 mb-2">8. Contact Us</h2>
              <p>If you have any questions about these Terms, please contact us at legal@resumemaster.app.</p>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}
