export const APP_NAME = 'ResumeMaster'
export const APP_DESCRIPTION = 'AI-Powered Resume Generator'
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || (process.env.NODE_ENV === 'development' ? 'http://localhost:3000' : '')

export const NAV_ITEMS = [
  { href: '/', label: 'Home' },
  { href: '/builder/resume', label: 'Resume Builder' },
  { href: '/builder/job', label: 'Job Analyzer' },
  { href: '/builder/preview', label: 'Preview' },
  { href: '/dashboard', label: 'Dashboard' },
  { href: '/pricing', label: 'Pricing' },
]

export const PRICING_PLANS = [
  {
    id: 'trial',
    name: '3-Day Trial',
    price: '1 Rs',
    priceAmount: 1,
    resumes: 'Unlimited',
    features: ['3 Days Full Access', 'AI Resume Tailoring', 'Job Analysis', 'Autopay Verification (Refundable)'],
  },
  {
    id: 'weekly',
    name: 'Weekly Access',
    price: '79 Rs',
    priceAmount: 79,
    resumes: 'Unlimited',
    features: ['7 Days Full Access', 'No Watermarks', 'Advanced AI Analysis', 'ATS Scoring', 'Priority Support'],
  },
  {
    id: 'monthly',
    name: 'Monthly Access',
    price: '129 Rs',
    priceAmount: 129,
    resumes: 'Unlimited',
    features: ['30 Days Full Access', 'Everything in Weekly', 'Priority 24/7 Support', 'Early Access to New Features'],
  },
]


export const FEATURES = [
  {
    title: 'AI Tailoring',
    description: 'Automatically tailor your resume for each job',
    icon: '🤖',
  },
  {
    title: 'ATS Optimization',
    description: 'Optimize for Applicant Tracking Systems',
    icon: '✅',
  },
  {
    title: 'One-Click Export',
    description: 'Download as PDF or share with one click',
    icon: '📄',
  },
  {
    title: 'Job Analysis',
    description: 'Analyze job postings to match requirements',
    icon: '🔍',
  },
  {
    title: 'Live Preview',
    description: 'See changes in real-time as you edit',
    icon: '👁️',
  },
  {
    title: 'Lightning Fast',
    description: 'Built with Next.js for optimal performance',
    icon: '⚡',
  },
]

export const FAQ_ITEMS = [
  {
    question: 'Is my data secure?',
    answer: 'Yes, we use industry-standard encryption and never share your data.',
  },
  {
    question: 'Can I export to different formats?',
    answer: 'Yes, you can export as PDF or share via a unique link.',
  },
  {
    question: 'Do you offer a free trial?',
    answer: 'Yes! We offer a 3-day trial with full access. To start, you must enable autopay, which can be cancelled at any time within the 3 days before any charge occurs.',
  },
  {
    question: 'Can I cancel anytime?',
    answer: 'Absolutely. You can manage your subscription and cancel autopay at any time directly from your dashboard settings.',
  },
  {
    question: 'How does AI tailoring work?',
    answer: 'Our AI analyzes job postings and tailors your resume to match key requirements.',
  },
  {
    question: 'Is customer support available?',
    answer: 'Yes, email support for Free plan, priority support for paid plans.',
  },
]

export const RESUME_SECTIONS = [
  'Personal Info',
  'Education',
  'Experience',
  'Skills',
  'Projects',
  'Certifications',
  'Languages',
]

export const ACTION_VERBS = [
  'Accelerated',
  'Achieved',
  'Analyzed',
  'Approved',
  'Arranged',
  'Assessed',
  'Assigned',
  'Assisted',
  'Assumed',
  'Assured',
  'Attained',
  'Boosted',
  'Built',
  'Calculated',
  'Completed',
  'Coordinated',
  'Created',
  'Decreased',
  'Defined',
  'Delivered',
  'Demonstrated',
  'Designed',
  'Developed',
  'Directed',
  'Earned',
  'Expanded',
  'Exceeded',
  'Executed',
  'Facilitated',
  'Generated',
  'Headed',
  'Identified',
  'Implemented',
  'Improved',
  'Increased',
  'Innovated',
  'Installed',
  'Instituted',
  'Instrumental',
  'Integrated',
  'Introduced',
  'Investigated',
  'Launched',
  'Led',
  'Leveraged',
  'Managed',
  'Maximized',
  'Modernized',
  'Negotiated',
  'Optimized',
  'Organized',
  'Orchestrated',
  'Pioneered',
  'Processed',
  'Produced',
  'Programmed',
  'Promoted',
  'Proposed',
  'Provided',
  'Reduced',
  'Redesigned',
  'Reorganized',
  'Reported',
  'Represented',
  'Researched',
  'Resolved',
  'Revamped',
  'Revitalized',
  'Secured',
  'Selected',
  'Shaped',
  'Simplified',
  'Solicited',
  'Solved',
  'Spearheaded',
  'Spoke',
  'Standardized',
  'Strengthened',
  'Structured',
  'Succeeded',
  'Supervised',
  'Supported',
  'Surpassed',
  'Surveyed',
  'Sustained',
  'Synthesized',
  'Targeted',
  'Transformed',
  'Transitioned',
  'Translated',
  'Tripled',
  'Undertook',
  'Unified',
  'Updated',
  'Upgraded',
  'Utilized',
  'Validated',
  'Verified',
  'Vitalized',
  'Visualized',
  'Volunteered',
  'Widened',
  'Won',
  'Worked',
  'Yielded',
]
